services:
  
  db:
    image: postgres:15-alpine
    container_name: stock_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  java-api:
    build: ./backend
    container_name: java_backend
    depends_on:
      - db
    ports:
      - "8083:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stock_market
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - UPLOAD_DIR=/app/uploads
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - uploads_data:/app/uploads
    networks:
      - app-network


  python-api:
    build: ./fast-api
    container_name: python_fastapi
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stock_market
    volumes:
      - uploads_data:/app/uploads
    networks:
      - app-network


  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:80"
    depends_on:
      - java-api
      - python-api
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


volumes:
  postgres_data:
  uploads_data:
